### ISSUE TITLE
Great example

### ISSUE THREAD

**Issue by harrwiss-swt** [tsuoanttila/custom-grid-demo#1]
This was exactly what I was looking for, hence it took some time to figure out what the buttons do and that "setEditorBuffered(false)" does the switch to the new Editor mode in Vaadin 7.6. 

Some issues I noticed beside your todo list:
- pressing Enter on the last row should go out of editor mode with save or go to the first like in the grid
- clicking outside the grid should go out of editor mode and do a save (or ask the user)
- styling of editable and not editable cells

**Comment by tsuoanttila** [comment]
At least for enter on the last row, the default comes from the Framework, but can be overridden in your custom editor event handler. 

For the focus you should be able to use the server focus listeners to notice focus going outside of Grid (and Editor components) and close the editor when that happens. 

Styling is not touched in this example, as this was meant only for the client-side modifications of the Editor and SelectionModel.
